### ISSUE TITLE
LSP Server crashing on curly quotes and emojis

### ISSUE THREAD

**Issue by yassere** [romefrontend/rome#736]
## Steps To Reproduce

With VS Code closed, run `./scripts/run-vscode-extension .`

After project initializes, add curly quotes or emojis to a file:
```js
// Can’t handle this comment
const foo = 'Or this “special” string';
const rocket = "Or this 🚀";
```

## Results

LSP Server crashes with a `JSON parse error`

**Comment by sebmck** [comment]
What’s the stack trace? Is it coming from the bridge? First guess it’s an update buffer call going from the LSP to a worker. Second guess is that we aren’t correctly counting string length when parsing LSP messages. We read a Content-Length header and cut the buffer off when it reaches that limit and parse it as JSON.

**Comment by yassere** [comment]
Yeah, it does look related to how we parse the messages.

<details>
  <summary>Stack Trace</summary>

```
JSON parse error {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"file:///Users/Yasser/Dev/rome/foo.ts","version":2},"contentChanges":[{"text":"// Can’t handle this comment\nconst foo = 'Or this “special” string';\nconst rocket = \"Or this 🚀\";"}]}}Content-
[Error: Expected Content-Length
  at ___R$$priv$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$parseHeaders (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:74:8)
  at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.process (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:649:24)
  at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.process (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:639:10)
  at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.process (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:676:10)
  at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.append (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:685:7)
  at append (project-rome/@romefrontend/core/server/commands/lsp.ts:33:13)
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.call (project-rome/@romefrontend/events/Event.ts:106:5)
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.dispatchRequest (project-rome/@romefrontend/events/BridgeEvent.ts:95:15)
  at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.handleMessageRequest (project-rome/@romefrontend/events/Bridge.ts:444:16)
  at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.handleMessage (project-rome/@romefrontend/events/Bridge.ts:394:9)
  at Object.sendMessage (project-rome/@romefrontend/events/bridgeCreators.ts:202:10)
  at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.sendMessage (project-rome/@romefrontend/events/Bridge.ts:357:7)
  at sendMessage (project-rome/@romefrontend/events/BridgeEvent.ts:201:16)
  at new Promise
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.call (project-rome/@romefrontend/events/BridgeEvent.ts:161:16)
  at Socket.call (project-rome/@romefrontend/core/client/commands/lsp.ts:44:31)
  at Socket.emit (events.js:203:12) generated source location
  at addChunk (_stream_readable.js:295:11) generated source location
  at readableAddChunk (_stream_readable.js:276:10) generated source location
  at Socket.push (_stream_readable.js:210:9) generated source location
  at Pipe.onStreamRead (internal/stream_base_commons.js:166:16) generated source location] {
  name: 'Error',
  ERROR_FRAMES: [ ... ]
}
✖ Fatal error occurred: Error: Expected Content-Length
    at ___R$$priv$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$parseHeaders
  (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:74:8)
    at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.process
  (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:649:24)
    at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.process
  (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:639:10)
    at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.process
  (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:676:10)
    at ___R$project$rome$$romefrontend$core$server$lsp$LSPServer_ts$default.append
  (project-rome/@romefrontend/core/server/lsp/LSPServer.ts:685:7)
    at append (project-rome/@romefrontend/core/server/commands/lsp.ts:33:13)
    at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.call
  (project-rome/@romefrontend/events/Event.ts:106:5)
    at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.dispatchRequest
  (project-rome/@romefrontend/events/BridgeEvent.ts:95:15)
    at
  ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.handleMessageRequest
  (project-rome/@romefrontend/events/Bridge.ts:444:16)
    at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.handleMessage
  (project-rome/@romefrontend/events/Bridge.ts:394:9)
    at Object.sendMessage (project-rome/@romefrontend/events/bridgeCreators.ts:202:10)
    at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.sendMessage
  (project-rome/@romefrontend/events/Bridge.ts:357:7)
    at sendMessage (project-rome/@romefrontend/events/BridgeEvent.ts:201:16)
    at new Promise
    at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.call
  (project-rome/@romefrontend/events/BridgeEvent.ts:161:16)
    at Socket.call (project-rome/@romefrontend/core/client/commands/lsp.ts:44:31)
    at Socket.emit (events.js:203:12) generated source location
    at addChunk (_stream_readable.js:295:11) generated source location
    at readableAddChunk (_stream_readable.js:276:10) generated source location
    at Socket.push (_stream_readable.js:210:9) generated source location
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:16) generated source location
[Info  - 9:58:52 PM] Connection to server got closed. Server will restart.
```
</details>

**Comment by sebmck** [comment]
Sweet. I'll work on a fix now and add some LSP parser tests.
